apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: keda
spec:
  releaseName: keda
  targetNamespace: keda
  interval: 30m
  dependsOn:
    - name: aws-load-balancer-controller
      namespace: flux-system
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/eks-keda-sqs-lab-sqs-keda
